import crypto from "crypto";
import { sendEmail } from "../config/mailer.js";
import { getRedisClient } from "../config/redis.js";
import {verifyEmailTemplate, verifyEmailText} from "../utils/emailTemplate/verifyEmailTemplate.js"

export const generateAndSendOTP = async (email, fullName) => {
  const redis = getRedisClient();
  if (!redis) throw new Error("Redis not initialized");

  const otpKey = `otp:${email}`;
  const countKey = `otp:count:${email}`;
  const lastRequestKey = `otp:last_request:${email}`;

  // check last resend time
  const lastRequest = await redis.get(lastRequestKey);
  if (lastRequest) {
    const remaining = 60 - (Date.now() - parseInt(lastRequest)) / 1000;
    if (remaining > 0) {
      throw new Error(
        `Please wait ${Math.ceil(remaining)}s before resending OTP.`
      );
    }
  }

  // check if OTP exists & valid(reuse same OTP)
  let otp = await redis.get(otpKey);
  if (otp) {
    console.log("Returning existing OTP(still valid)");
  } else {
    // check rate limit
    const count = await redis.get(countKey);
    if (count && parseInt(count) >= 3) {
      throw new Error(
        "Maximum OTP requests reached. Try again after 10 minutes"
      );
    }

    // generate new OTP
    otp = crypto.randomInt(100000, 999999).toString();
    const hashedOtp = crypto.createHash("sha256").update(otp).digest("hex");

    await redis.set(otpKey, hashedOtp, "EX", 10*60) // 10 min expiry

    // increment counter
    await redis.incr(countKey)
    await redis.expire(countKey, 10*60) // 10 min window
  }

  // update last request timestamp
  await redis.set(lastRequestKey, Date.now().toString(), "EX", 60) // 1 min cooldown

  // send email
  await sendEmail({
    to: email,
    subject: "Verify your email - Lily 🌱",
    html: verifyEmailTemplate(fullName, otp),
    text: verifyEmailText(fullName, otp)
  })
  console.log(`OTP sent to ${email}`);
  return otp;
};

// verifyOTP service 
export const verifyOTP = async(email, enteredOtp, user) =>{
  const redis = getRedisClient()
  if(!redis) throw new Error("Redis not initialized")
  
  const otpKey = `otp:${email}`
  const storedHashedOtp = await redis.get(otpKey)

  if(!storedHashedOtp) return false;

  const hashedEnteredOtp = crypto
    .createHash("sha256")
    .update(enteredOtp)
    .digest("hex")
  
  if(storedHashedOtp !== hashedEnteredOtp) return false

  // OTP verified - clear Redis data
  await redis.del(otpKey)
  await redis.del(`otp:last_request:${email}`)
  await redis.del(`otp:count:${email}`)

  // update user in DB
  user.isVerified = true;
  await user.save();

  return true;
}















// otp generation & send email function
// export const generateAndSendOTP = async (user) => {
//   const otp = crypto.randomInt(100000, 999999).toString();
//   const hashedOTP = crypto.createHash("sha256").update(otp).digest("hex");
//   const otpExpires = Date.now() + 10 * 60 * 1000;

//   user.otp = hashedOTP;
//   user.otpExpires = otpExpires;
//   await user.save();

//   await sendEmail({
//     to: user.email,
//     subject: "Verify your email - Lily 🌱",
//     html: `
//     <div style="font-family: Arial, sans-serif; background-color: #f4f4f4; padding: 20px;">
//       <div style="max-width: 600px; margin: auto; background: #fff; padding: 30px; border-radius: 8px;">
//         <p style="font-size: 16px;"><strong>Greeting's, ${user.fullName}</strong></p>
//         <div style="background-color: #f9f9f9; padding: 15px; border-radius: 5px; margin-top: 10px;">
//           <p>Your verification code is: <b style="font-size: 14px;">${otp}</b></p>
//           <p>It is valid for 10 minutes.</p>
//           <p>Thank you for registering with Lily!</p>
//         </div>
//         <p style="margin-top: 30px; font-size: 12px; color: #888;">This email was sent automatically generated by Lily backend team.</p>
//       </div>
//     </div>
//   `
//     // text: `Hi ${user.fullName},\n\nYour verification code is: ${otp}
//     // \nIt is valid for 10 minutes.
//     // \n\nThank you for registering with Lily!`,
//   });

//   console.log(`OTP sent to ${user.email}`);
//   return otp;
// };

// otp verification function
// export const verifyOTP = async (user, enteredOtp) => {
//   const hashedEnteredOtp = crypto
//     .createHash("sha256")
//     .update(enteredOtp)
//     .digest("hex");

//   if (
//     user.otp !== hashedEnteredOtp ||
//     !user.otpExpires ||
//     user.otpExpires < Date.now()
//   ) {
//     return false;
//   }

//   user.otp = undefined;
//   user.otpExpires = undefined;
//   user.isVerified = true;
//   await user.save();

//   return true;
// };

// Generate and send OTP for forgot password
// export const generateAndSendResetOTP = async (user) => {
//   const otp = crypto.randomInt(100000, 999999).toString();
//   const hashedOTP = crypto.createHash("sha256").update(otp).digest("hex");
//   const otpExpires = Date.now() + 10 * 60 * 1000;

//   user.resetOtp = hashedOTP;
//   user.resetOtpExpires = otpExpires;
//   await user.save();

//   await sendEmail({
//     to: user.email,
//     subject: "Password Reset Code - Lily 🌱",
//     text: `Hi ${user.fullName},\n\nYour password reset code is: ${otp}
//     \nIt will expire in 10 minutes.
//     \n\nIf you didn’t request this, please contact us.`,
//   });

//   console.log(`Reset OTP sent to ${user.email}`);
//   return otp;
// };

// // Verify reset OTP
// export const verifyResetOTP = async (user, enteredOtp) => {
//   const hashedEnteredOtp = crypto
//     .createHash("sha256")
//     .update(enteredOtp)
//     .digest("hex");

//   if (
//     user.resetOtp !== hashedEnteredOtp ||
//     !user.resetOtpExpires ||
//     user.resetOtpExpires < Date.now()
//   ) {
//     return false;
//   }

//   user.resetOtp = undefined;
//   user.resetOtpExpires = undefined;
//   await user.save();

//   return true;
// };